### ISSUE TITLE
[USER FEEDBACK] Improvements to the UI of probe-desktop

### ISSUE THREAD

**Issue by comradekingu** [ooni/probe#1123] opened 2020-04-18 22:40 UTC
Running 3.0.0-rc.7 on Linux|GNU.

Can't click "Learn more" in "Heads-Up" screen (nr 2.)
Don't do a pop-up to show a check-mark.

If I click "Change defaults", I get to "Settings", with no obvious way of getting back to the tutorial.
OK, it is either "Settings", or "Dashboard", but I would rather it was just dashboard with the info saying to go to settings unless. Easier to use mindlessly then.

"Go back" overlaps the squid in "Default settings" screen.

"Can't click "OONI's data policy"

Settings look unloved. Re-states version info. (Which is always present bottom left)

Blue from setup background gone in dashboard.
- No indication of what tests have been ran or not.
 Gray out tests that have yet to run?
Combine test result data with Websites? Could be done with settings icon bottom right, as one of the tiles, no side-menu.

Getting to settings first time is Electron-slow.

"What does "Hard reset" in "About OONI do"? I imagine reset everything to defaults? (It did, but why is it in "About", is it only for debugging?
"Websites" and "Middleboxes" colours are too close. (I did a reset and now they are not. Does the colour change if the test has been performed already).

"Circumvention" icon overshoots the panel, and overlaps the text.
"Instant messaging" overshoots the question-mark.
Too many decimals on network speed test.
No indication of how much one needs to get 8k, or where the results places one relative to the different ones, or an average.

Most of my gripes were related to language, which gets a solid 3 out of 5. Hope to see this project on Weblate. Would help out. Answered because @ekcnl asked, and you also have nice people working at OONI. Had it written down, but rebooted it.

Bonus: Got the Instant messaging test to crash.
Said Running:
Test complete. So clicked to end it after a while of pondering this juxtaposition.

Then says:
Stopping test… (Only without it being an ellipsis)
Dashboard.Running.Notice.Stopping
test complete
<details>
starting facebook_messenger
got ip 31.13.72.36 for service b_graph
got ip 31.13.72.36 for service b_api
got ip 31.13.72.5 for service edge
got ip 31.13.72.12 for service external_cdn
got ip 31.13.72.12 for service scontent_cdn
got ip 31.13.72.8 for service star
got ip 31.13.72.3 for service stun
31.13.72.36 is in FB's ASN
31.13.72.36 is in FB's ASN
31.13.72.5 is in FB's ASN
31.13.72.12 is in FB's ASN
31.13.72.12 is in FB's ASN
31.13.72.8 is in FB's ASN
31.13.72.3 is in FB's ASN
service b_api DNS consistency: true
service b_graph DNS consistency: true
service edge DNS consistency: true
service external_cdn DNS consistency: true
service scontent_cdn DNS consistency: true
service star DNS consistency: true
service stun DNS consistency: true
tcp success to b_graph at 31.13.72.36:443
tcp success to b_api at 31.13.72.36:443
tcp success to external_cdn at 31.13.72.12:443
tcp success to edge at 31.13.72.5:443
tcp success to scontent_cdn at 31.13.72.12:443
tcp success to star at 31.13.72.8:443
service b_api DNS consistency: true
service b_api TCP reachability: true
service b_graph DNS consistency: true
service b_graph TCP reachability: true
service edge DNS consistency: true
service edge TCP reachability: true
service external_cdn DNS consistency: true
service external_cdn TCP reachability: true
service scontent_cdn DNS consistency: true
service scontent_cdn TCP reachability: true
service star DNS consistency: true
service star TCP reachability: true
doing a random endpoint
starting whatsapp test
whatsapp: success HTTP connecting to https://v.whatsapp.net/v2/register
saw no errors in Whatsapp's registration server
whatsapp: success HTTP connecting to http://web.whatsapp.com/
whatsapp: success HTTP connecting to https://web.whatsapp.com/
saw no errors in Whatsapp Web
whatsapp: 1 hostnames
(2) e15.whatsapp.net hostname: e15.whatsapp.net
(1) e15.whatsapp.net ipv4: 34.194.71.217
(2) e15.whatsapp.net hostname: e15.whatsapp.net
(1) e15.whatsapp.net ipv4: 34.194.255.230
(2) e15.whatsapp.net hostname: e15.whatsapp.net
(1) e15.whatsapp.net ipv4: 34.192.181.12
(2) e15.whatsapp.net hostname: e15.whatsapp.net
(1) e15.whatsapp.net ipv4: 34.193.38.112
dns_many() found 4 ips
saw no errors in Whatsapp's endpoints (DNS)
tcp success to 34.192.181.12:5222
removing e15.whatsapp.net from blocked_hostnames
tcp success to 34.192.181.12:443
removing e15.whatsapp.net from blocked_hostnames
tcp success to 34.194.255.230:5222
removing e15.whatsapp.net from blocked_hostnames
tcp success to 34.194.71.217:443
removing e15.whatsapp.net from blocked_hostnames
tcp success to 34.193.38.112:5222
removing e15.whatsapp.net from blocked_hostnames
tcp success to 34.194.255.230:443
removing e15.whatsapp.net from blocked_hostnames
tcp success to 34.193.38.112:443
removing e15.whatsapp.net from blocked_hostnames
tcp success to 34.194.71.217:5222
removing e15.whatsapp.net from blocked_hostnames
saw no errors in Whatsapp's endpoints (TCP)
</details>
from terminal:
<details>
22:36:56.716 › stdout:  {"fields":{"type":"engine"},"level":"info","timestamp":"2020-04-18T22:36:56.716088745Z","message":"removing e15.whatsapp.net from blocked_hostnames"}
22:36:56.717 › stdout:  {"fields":{"type":"engine"},"level":"info","timestamp":"2020-04-18T22:36:56.716100536Z","message":"saw no errors in Whatsapp's endpoints (TCP)"}
22:36:56.717 › stdout:  {"fields":{"eta":-1,"key":"nettests.WhatsApp","percentage":0.9833333333333333,"type":"progress"},"level":"info","timestamp":"2020-04-18T22:36:56.716454702Z","message":"ending the test"}
22:36:56.717 › stdout:  {"fields":{"eta":-1,"key":"nettests.WhatsApp","percentage":1,"type":"progress"},"level":"info","timestamp":"2020-04-18T22:36:56.716499659Z","message":"test complete"}
22:36:56.963 › exited with code 0
22:37:47.622 › Runner: terminating the ooniprobe process
</details>

**Comment by hellais** [comment] 2021-05-14 11:17
Thanks for reporting these issues and apologies for getting back to you so late on them.

I am going to attempt to reproduce all the issues you have reported and if there are ones still pending open follow up issues.

> Can't click "Learn more" in "Heads-Up" screen (nr 2.)

This is resolved for me. It opens the link in a browser as expected.

> Don't do a pop-up to show a check-mark.

I don't understand this comment.

> If I click "Change defaults", I get to "Settings", with no obvious way of getting back to the tutorial.
> OK, it is either "Settings", or "Dashboard", but I would rather it was just dashboard with the info saying to go to settings unless. Easier to use mindlessly then.

This is because it's the last step of the onboarding and once you are there any button you click will finalise the onboarding.

> "Go back" overlaps the squid in "Default settings" screen.

Can you share a screenshot of this? It doesn't appear to overlap at my screen resolution.

> "Can't click "OONI's data policy"

I can't reproduce this. Similarly to the "Learn more" button it works as expected on macOS. I wonder at this point if it's a linux specific issue. To validate if that is the case I opened: https://github.com/ooni/probe/issues/1479.

> Settings look unloved. Re-states version info. (Which is always present bottom left)

I agree we can make some improvements to it, though I am not sure how this is directly actionable.

> Blue from setup background gone in dashboard.

Can you clarify what you mean by this?

> No indication of what tests have been ran or not.
> Gray out tests that have yet to run?

I don't understand what this means. Can you clarify in which screen you are on and what you find confusing?

> Combine test result data with Websites? Could be done with settings icon bottom right, as one of the tiles, no side-menu.

I don't understand this either can you perhaps share a screenshot of this?

> Getting to settings first time is Electron-slow.

I documented some improvements for this here: https://github.com/ooni/probe/issues/1480

> "What does "Hard reset" in "About OONI do"? I imagine reset everything to defaults? (It did, but why is it in "About", is it only for debugging?

This was left while we were debugging and developing the app initially. We should perhaps remove this button from future versions.

https://github.com/ooni/probe/issues/1481

> "Websites" and "Middleboxes" colours are too close. (I did a reset and now they are not. Does the colour change if the test has been performed already).

This is very strange. Do you perhaps have a screenshot of this?

> "Circumvention" icon overshoots the panel, and overlaps the text.
> "Instant messaging" overshoots the question-mark.

Are these still the case with the new dashboard layout? I believe this should be fixed now.

> Too many decimals on network speed test.

Which value are you referring to specifically? We have 1 decimal point for upload and download speeds, which is seems reasonable.

> No indication of how much one needs to get 8k, or where the results places one relative to the different ones, or an average.

This is a great point, though it's kind of a major feature and requires also backend analysis work. I documented this feature request here: https://github.com/ooni/probe/issues/1482.

> Most of my gripes were related to language, which gets a solid 3 out of 5. Hope to see this project on Weblate. Would help out. Answered because @ekcnl asked, and you also have nice people working at OONI. Had it written down, but rebooted it.

The app is translated on transifex: https://www.transifex.com/otf/ooniprobe/translate. If you are interested in joining the translation group let us know and we can get you added to the reviewers for your language (what language is it BTW?).

> Bonus: Got the Instant messaging test to crash.
> Said Running:
> Test complete. So clicked to end it after a while of pondering this juxtaposition.

This is hard to reproduce given this information.

> Then says:
> Stopping test… (Only without it being an ellipsis)
> Dashboard.Running.Notice.Stopping
> test complete

This was a missing translated string. It's now fixed.

**Comment by comradekingu** [comment] 2021-05-14 13:21
@hellais
I am actually already a Ooni translator. And you will maybe remember me by my complaining about Transifex being an absolute joke, and a worse one at that for someone pertaining to care about invasive tracking. It isn't a good look.

Be that as it may, I am also the sort of person to do something about it, so I have stopped using Transifex. Can't log in without accepting their terms. I can help you set up shop with Weblate, but I am far from a grok. The nb_NO translation has subsequently failed. I at-least care about that. It was never that my contributions were meaningful, and you can continue being mediocre at language as a project, but you don't have to.

That is just where I am at with contemplating sinking real time and effort into improving matters.

I entirely forgot I had tested this, and wrote #1483 thinking I might as-well get a new take before figuring out what I did (which isn't easy I'll admit).

I'll get it installed on Linux and report back in due time.

**Comment by hellais** [comment] 2021-05-27 10:25
Yeah we don't currently make official debian packages for the OONI Probe desktop, so on linux currently the only official installation method is probe-cli.

We are tracking the work that needs to be done for linux here:
* https://github.com/ooni/probe/issues/1498
* https://github.com/ooni/probe/issues/1498

I am going to close this issue, but feel free to open any follow up issues with any other problem you encounter.

Thanks again for testing OONI Probe!

**Closed by hellais** 2021-05-27 10:25 UTC
Labels: bug, ooni/probe-desktop, platform/linux, priority/medium, user feedback
