### ISSUE TITLE
Add support for automatic deletion of measurements

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#2189] opened 2022-07-26 14:10 UTC
During the July 2022 OONI Community Meeting, we raised the following question:

> Currently in the OONI probe app you can delete all measurements. Would you like to also have the option to manually delete specific measurements or automatically (e.g., based on some time constraints like "two days")?

In response, community members expressed their desire to have the following 2 options:

- Manually delete specific measurements (default setting);

- Automatically have (specific or all) measurements deleted (excluding non-uploaded measurements).

As OONI Probe already supports the manual deletion of specific measurements, it would be a question of adding support for the automatic deletion of  (specific or all) measurements (excluding non-uploaded measurements).

**Comment by hellais** [comment] 2022-07-26 14:58
This is a duplicate of: https://github.com/ooni/probe/issues/1983

**Closed by hellais** 2022-07-26 14:58 UTC
Labels: enhancement, ooni/probe-mobile, ooni/probe-desktop
