### ISSUE TITLE
Add support to periodically perform tests

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#989] opened 2020-01-30 18:41 UTC
OONI Probe on mobile should have the capability to periodically perform and (re-)run all tests.

Having longitudinal network measurements for all tests (not only for the Web Connectivity test) provide an important internet censorship study and.

**Comment by hellais** [comment] 2020-01-30 22:47
This is a duplicate of : ooni/probe#955 and ooni/probe#916.

Closing.

**Closed by hellais** 2020-01-30 22:47 UTC
Labels: duplicate
