### ISSUE TITLE
community request: throttling measurement methodology

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1680] opened 2021-06-11 09:15 UTC
Over the years, community members have frequently expressed the need for a new nettest designed to measure throttling. This was also more recently requested during RightsCon sessions. 

Currently (to my knowledge), an open methodology for measuring throttling doesn't exist yet, and defining and measuring throttling remains an ongoing research question. 

Some things to take into consideration:

* What do we mean by throttling? Are we referring to throttling towards specific services? We first need to come up with a specification and based on that evaluate which methodology makes sense (and is feasible).
* Community members frequently report throttling towards popular social media services, such as Facebook, Twitter, YouTube, Instagram, etc.
* Sometimes community members also report "generic throttling" to communicate unusually slow internet speed (without being specific to services). However, these reports often emerge during protests and other events, when it's possible that this could be explained by network congestion and other factors. 

Currently, we have the NDT and DASH tests which are run against M-Lab servers. However, these tests are not sufficient for measuring throttling because:
* We don't have a baseline to compare these measurements against;
* These tests are usually user-initiated, and there is often testing bias involved (i.e. people often only run tests when they notice that their internet connectivity is unusually slow, instead of running them all the time).

We would ideally need a large volume of stable measurements (collected from the same AS network) over a long period of time in order to be able to derive statistically-useful information. While the OONI Probe apps support automated testing, the NDT and DASH tests are (currently) not included in automated runs because that would be too bandwidth-intensive. So it remains quite unclear how to collect large volumes of stable measurements from user-initiated tests. 

If we were to measure throttling towards a specific service (e.g. Facebook), we would need that company to **host a measurement backend** that we can run tests against.  In this scenario, the OONI Probe DASH test (for example) would **run tests against M-Lab servers + Facebook's measurement backend**. That way, we would be able to compare the 2 measurements in order to be able to start measuring potential throttling. Convincing companies to host such a measurement backend though can be challenging.

**Comment by hellais** [comment] 2021-06-11 09:17
Related to: https://github.com/ooni/probe/issues/646

**Comment by bassosimone** [comment] 2023-03-09 08:29
I am going to close this issue as a duplicate of https://github.com/ooni/ooni.org/issues/1296.

**Closed by bassosimone** 2023-03-09 08:29 UTC
Labels: duplicate, epic, priority/medium, new nettest, discuss, user feedback
