### ISSUE TITLE
Support dark mode in OONI Probe mobile apps

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#880] opened 2019-09-03 10:32 UTC
We received an email from an OONI Probe user requesting that we add support for dark mode in the mobile apps (the app is "too white" and hurts their eyes).

**Comment by lorenzoPrimi** [comment] 2020-04-27 16:34
Duplicate of https://github.com/ooni/probe/issues/925

**Closed** 2020-08-31 10:44 UTC
Labels: enhancement, ooni/probe-mobile, ux
