### ISSUE TITLE
Move Explorer link from nested setting to a button on the test result page

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1161] opened 2020-05-18 14:24 UTC
Similarly to OONI Probe Desktop, I think it would work better if we move the "Copy Explorer URL" option from the nested setting to a button on the test result page in the OONI Probe mobile app.

For example, a test result page on Desktop includes a button that makes it easier to find the relevant OONI Explorer measurement link.

See:

![psiphon](https://user-images.githubusercontent.com/8290574/82224179-d71b0a00-9923-11ea-80a7-a721b5bfb5e5.png)

To enable OONI Probe Mobile users to more easily find the OONI Explorer link (and to have more UI consistency between the two apps), I propose moving this option out of the nested setting inside the test result page, and into a button on that page (similarly to Desktop, as illustrated above).

I also propose that we use the same copy for this button as OONI Probe Desktop.

**Comment by agrabeli** [comment] 2020-05-18 14:25
cc' @hellais @sarathms

**Comment by agrabeli** [comment] 2020-05-18 14:25
This is similar to https://github.com/ooni/probe/issues/1160.

**Comment by hellais** [comment] 2020-05-18 14:36
Closing this as duplicate of: https://github.com/ooni/probe/issues/1160#issuecomment-630224213

**Closed by hellais** 2020-05-18 14:36 UTC
Labels: discuss, ooni/probe-mobile, ux
