### ISSUE TITLE
Avoid running same tests (decks or nettests)

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#674] opened 2016-11-12 10:41 UTC
By default ooniprobe will run the default test deck or the deck(s) specified by the user upon
successful initialization (setup wizard completion). Users will see no measurements running (in the measurements page) and (usually) instruct ooniprobe to run decks or nettests that have been already scheduled to run, leading in having concurrent tests (same decks or nettests) running.

At this point we should ensure that a user:

- [ ] Gets a confirmation box to run decks and nettests that are already running or scheduled to run on the same day.
- [x] View the list of scheduled tasks even if they haven't yet started.
- [x] Can (force) stop a test running in the measurements page. `Duplicate of`: https://github.com/TheTorProject/ooni-probe/issues/590

**Comment by hellais** [comment] 2017-04-05 14:16
In the new web UI we keep track of running decks so the user will not be able to run a test they have already manually started and will see in the UI that a test is currently running (via schedule).

**Comment by anadahz** [comment] 2017-04-06 12:18
I think that this issue is important since the user is still not getting any prompt of what is happening in the case described in this issue. For instance is there another test running, is this test going to be scheduled and run upon completion of the current running test or both?

Also the user cannot (force) stop a running test (or deck) in the measurements page.

The scheduled tasks/tests are now visible in the web UI (marked as resolved).

**Comment by hellais** [comment] 2017-04-06 12:29
The UI shows that the scheduled deck is already running and that they have already manually started a deck

**Comment by hellais** [comment] 2017-04-06 12:32
The ability to stop tests or decks is a duplicate of #590

**Comment by anadahz** [comment] 2017-04-06 13:56
> The UI shows that the scheduled deck is already running and that they have already manually started a deck

I can't reproduce this behavior. When I add a new test for instance when  I trigger web_connectivity test for a specific URL while another web_connectivity test is running (on the global test list) I get no notifications or any sort of prompt.
I'm not sure if this is a browser specific issue (tested on Chjromium version 57.0.2987.98).

**Comment by hellais** [comment] 2017-04-06 14:28
> I can't reproduce this behavior. When I add a new test for instance when I trigger web_connectivity test for a specific URL while another web_connectivity test is running (on the global test list) I get no notifications or any sort of prompt.

You will not be able to manually trigger another test only when you manually run all the deck.

I think showing that a custom test is running for a custom URL would be confusing and not that useful (if a user chose to test a specific URL, when they will re-run another one, it's most likely because they want to test another site or retest it).

**Comment by anadahz** [comment] 2017-04-06 16:19
> You will not be able to manually trigger another test only when you manually run all the deck.

> I think showing that a custom test is running for a custom URL would be confusing and not that useful (if a user chose to test a specific URL, when they will re-run another one, it's most likely because they want to test another site or retest it).

I may be confused but to clarify my use case: I didn't run any deck custom, there is already a deck running (the web deck) ideally a user should get a visual notification that a test has been triggered/queued for execution. What is happening now instead (in ooniprobe version 2.2.0) is that there is no prompt or anything showing that this/a test has started or any action has been trigerred. I think this can be very confusing as a user may not be able to realize if the "click" has triggered any action or if there is network connectivity to the ooniprobe's web GUI.

I hope that makes it a bit more clear.

**Comment by hellais** [comment] 2018-09-17 16:38
Issue moved to [ooni/probe-legacy #35](https://github.com/ooni/probe-legacy/issues/35) via [**ZenHub**](https://www.zenhub.com/)

**Closed** 2018-09-17 16:38 UTC
Labels: enhancement
