### ISSUE TITLE
Improve manual measurement upload performance

### ISSUE THREAD

**Issue by hellais** [ooni/probe#861] opened 2019-06-07 15:36 UTC
Currently the performance of the measurement manual upload feature is really bad.

I ran a couple of tests and it took me on a fairly fast network (~ 21 Mbit upload) a long time to manually upload measurements.
* To upload a web_connectivity result with 14 URLs (total 1.4MB) it took me a total of 77s
* To upload a web_connectivity result with 18 URL (total 1.7MB) it took me 79s

I believe this is due to the fact that we create a new report for every individual measurement (as opposed to making a single report and then appending to it as we do when you run a test).
This means that when you need to upload 10 measurements you do:
```
URL(1): a. create report b. upload measurement c. close report
URL(2): a. create report b. upload measurement c. close report
…
URL(10): a. create report b. upload measurement c. close report
```

This results in 3x the number of roundtrips as you could get away with by for example opening it once at the beginning and then just appending to the same report_id.

Some possible ways around this problem include:

1. Adding the ability to perform single request measurement upload (see: https://github.com/ooni/spec/blob/master/backends/bk-003-collector.md#34-submitting-single-measurements-using-a-single-api-call, though only the golang collector supports it)
2. Creating a single report and then appending to that one as part of the upload workflow
3. Parallelising the report upload

I think 3 is nice because it would allow us to use this approach also when we switch to the single request measurement upload method of the new collector.

If we don't address this as part of 2.1.0 we should at least keep this in mind as users may complain about it.

**Comment by bassosimone** [comment] 2019-06-07 15:51
> This results in 3x the number of roundtrips as you could get away with [...]

Whatever latency added by opening the connection, performing the TLS handshake, sending the request along with the body, is multiplied by three in this scenario.

> 1. Adding the ability to perform single request measurement upload

This improves the situation because we remove two negotiations out of three per transaction. It is slightly better than opening a report, submitting many measurements, and then closing the report by a constant factor represented by opening the report and closing the report.

> [...] though only the golang collector supports it)

I believe the correct way forward here is to implement this functionality in the legacy collector. I can take care of implementing this functionality, if that's helpful.

I believe that making a feature we need now conditional to another feature such as the Go collector, which is quite complex to roll out safely, may lead to further delays.

> I think 3 is nice because it would allow us to use this approach also when we switch to the single request measurement upload method of the new collector.

I am not super excited about this proposal (and in a similar fashion I am not happy about running measurements in parallel by default) because we have users on very different networks.

We have seen recent issues opened for OONI not being reliable enough on bad networks, see e.g. https://github.com/ooni/probe-android/issues/225.

Therefore, making parallelism upload the default is a solution that is going to make the life of some users more pleasant and the life of others much less pleasant.

> If we don't address this as part of 2.1.0 we should at least keep this in mind as users may complain about it.

I'd vote for releasing 2.1.0 unless there are serious regressions. And I'd vote for being honest with our users and clearly communicate them that this is the first iteration of the feature. I think it's better to have a not perfect implementation out next Monday than delaying further.

**Comment by bassosimone** [comment] 2019-06-11 09:24
One of the main aspects mentioned here is the single-measurement submission story. I have created issue #863 to track my work related to make this story possible with all possible collectors.

**Comment by bassosimone** [comment] 2019-07-01 17:16
> I'm going to work on #861 initially.

I am still working on #861, however it seems rolling out the single measurement upload mechanism is going to be more complex than expected.

> Then, I'll return here and see if further action is required or not.

Hence, here's another idea. Change the implementation of mkcurl to allow reusing easy handles, change the implementation of mkcollector to allow resubmitting using a specific easy handle and such that resubmitting also reuses a saved-into-a-variable report ID and, boom, we can basically cut all the performance issues documented here without touching the server side.

**Comment by bassosimone** [comment] 2019-07-22 08:18
I've done progress by implementing faster measurement resubmission in measurement-kit/mkcollector#25. Now I need to modify the API in mkall-ios and android-libs such that we can reuse the same CURL easy handle and the same report ID there. The functionality that decides whether to open a new report or keep the same report is in measurement-kit/mkcollector#25. So, the only changes required to attain this goal are: (1) making sure that we remove the serialised measurement from the constructor and (2) using the new code in the implementation. I will need to have a chat with @lorenzoPrimi to coordinate on how to use this new functionality in the apps.

**Comment by bassosimone** [comment] 2019-07-25 10:00
Implemented iOS in https://github.com/measurement-kit/mkall-ios/pull/25. Android still TODO.

**Comment by bassosimone** [comment] 2019-07-25 22:56
Now being tested for iOS at https://github.com/ooni/probe-ios/pull/302.

**Comment by bassosimone** [comment] 2019-07-26 13:58
I've starting sketching out Android: https://github.com/measurement-kit/android-libs/pull/78. I will follow a plan similar to the iOS one (see https://github.com/measurement-kit/mkall-ios/pull/25) so that I can start having an experimental branch for OONI for Android.

**Comment by bassosimone** [comment] 2019-07-26 23:33
Done also for Android here: https://github.com/ooni/probe-android/pull/247. What's next? Make sure that the code is sane, write more tests, do more QA, merge all the open PRs.

**Comment by bassosimone** [comment] 2019-08-29 08:45
We've merged https://github.com/measurement-kit/mkall-ios/pull/25 and https://github.com/measurement-kit/android-libs/pull/78, which implement fast resubmission for both Android and iOS. The new version of the apps will use this code. I'm going to close this issue because, AFAICT from implementing the code and testing it, the issue has been fixed. Please, reopen in case of relapse.

**Closed by bassosimone** 2019-08-29 08:45 UTC
Labels: enhancement
