### ISSUE TITLE
OONI test specifications (ooni-spec) should be added to the main OONI documentation

### ISSUE THREAD

**Issue by anadahz** [ooni/probe#467] opened 2016-03-16 18:28 UTC
https://ooni.torproject.org/docs/
https://ooni.readthedocs.org/en/latest/index.html

**Comment by hellais** [comment] 2020-01-16 17:33
This is a duplicate of: https://github.com/ooni/ooni.org/issues/235

**Closed by hellais** 2020-01-16 17:33 UTC
Labels: documentation
