### ISSUE TITLE
It's not possible to view logs when a test fails

### ISSUE THREAD

**Issue by hellais** [ooni/probe#857] opened 2019-04-23 12:03 UTC
## Expected Behavior

If a test fails it should be possible to inspect the logs for the failing test in order to better troubleshoot the problem.

## Actual Behavior

When you tap on a row of a failed test you are prompted to re-run the test, but it's not possible to see the logs

**Comment by hellais** [comment] 2019-04-23 12:03
I guess we should probably also come up with some UI pattern for support this.

cc @holantonela @elioqoshi

**Comment by lorenzoPrimi** [comment] 2019-04-23 12:56
Duplicate of https://github.com/ooni/probe/issues/850

**Closed by lorenzoPrimi** 2019-04-23 12:56 UTC
Labels: Bug, UX

**Comment by hellais** [comment] 2019-04-23 13:02
In which version of the app is this shipped in?

**Comment by lorenzoPrimi** [comment] 2019-04-23 13:03
Will be shipped as part of 2.1 in the next days
