### ISSUE TITLE
Web connectivity tests are not completely executing

### ISSUE THREAD

**Issue by nunesgh** [ooni/probe#1311] opened 2020-12-13 22:49 UTC
## Expected Behavior
I have selected 22 website categories for probe-cli and 20 for probe-android, in both cases without a time limit. As used to be the case, I expected a couple of thousands of websites to be probed in each case.

## Actual Behavior
Until 30 November, probe-cli would output about 16,200 lines during execution, including all tests (about 15,900 lines for web connectivity tests only). From 01 December, the log dropped to about 1,500 lines, including all tests (about 1,300 lines for web connectivity tests only).

Until 05 December, probe-android would probe about 2,300 websites. From 11 December, it dropped to 100 websites.

## Steps to Reproduce the Problem
In the case of probe-cli, I think this issue was introduced on v3.0.11. I have already updated to v3.1.0 and the issue persists.

In the case of probe-android, I'm currently running v2.8.0-beta.1, from F-Droid. I think the previous v2.7.1 did not present this issue.

Also important is that I run probe-cli and probe-android on different ASNs.

## Specifications

  - Versions: probe-cli v3.0.11 and v3.1.0, probe-android v2.8.0-beta.1
  - Platform: Debian 10, Android 9

**Comment by bassosimone** [comment] 2020-12-15 16:01
Thank you so much for letting us know about this issue @nunesgh! (And thank you for spending the time to document your issue so well, I really appreciated it! :-)

It seems the problem you saw was caused by a configuration in our backend, which should be fixed by https://github.com/ooni/api/commit/724a8f492ff5ee5655713927238e149f4dd1601e.

As such, I am going to close this issue now. Please, reopen if needed.

**Closed by bassosimone** 2020-12-15 16:01 UTC
Labels: effort/XS, interrupt, priority/medium

**Comment by nunesgh** [comment] 2020-12-17 00:25
Thank you for providing us this important service!
