### ISSUE TITLE
Probe-Desktop: Ability to try to re-upload results that were not uploaded.

### ISSUE THREAD

**Issue by xhdix** [ooni/probe#1320] opened 2021-01-08 14:38 UTC
![image](https://user-images.githubusercontent.com/12384263/104027178-127e8780-51d8-11eb-9c49-50e1ca8501eb.png)

**Comment by hellais** [comment] 2021-02-01 14:34
This is a duplicate of: https://github.com/ooni/probe/issues/950

**Closed by hellais** 2021-02-01 14:34 UTC
