### ISSUE TITLE
Update the GeoIP database of the mobile apps?

### ISSUE THREAD

**Issue by hellais** [ooni/probe#1019] opened 2020-02-17 15:51 UTC
Currently the WhatsApp test is reporting false positives because of bad GeoIP data.

**Comment by bassosimone** [comment] 2020-02-21 11:22
Took me a while to update this issue because I was "locked on a mutex". With @lorenzoPrimi we have checked into the version of the database that is currently part of the measurement-kit/android-libs `aar` file that ships with the OONI app. The version of such database is up to date.

The root cause of the WhatsApp false positives is actually https://github.com/ooni/probe-engine/issues/341.

**Closed by bassosimone** 2020-02-21 11:22 UTC
Labels: bug, discuss, effort/XS, ooni/probe-mobile, priority/high
