### ISSUE TITLE
Improve discoverability of the Data and Copy explorer URL buttons on mobile

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1160] opened 2020-05-18 14:19 UTC
We should research how we can make the Data and Copy Explorer URL buttons that are now under the option button in the top right corner more discoverable.

Apparently some users do not discover those options.

---
Original comment from @agrabeli was:

Similarly to OONI Probe Desktop, I think it would work better if we move the data from the nested setting to a button on the test result page in the OONI Probe mobile app.

For example, a test result page on Desktop includes a button that makes it easier to access the raw data (from that specific test). 

See:

![psiphon](https://user-images.githubusercontent.com/8290574/82223673-3debf380-9923-11ea-95c2-04266c10bd9a.png)

To enable OONI Probe Mobile users to more easily find the raw measurement data (and to have more UI consistency between the two apps), I propose moving that raw data out of the nested setting inside the test result page, and into a button on that page (similarly to Desktop, as illustrated above).

**Comment by agrabeli** [comment] 2020-05-18 14:20
cc' @hellais @sarathms

**Comment by hellais** [comment] 2020-05-18 14:35
After discussing this with @agrabeli it's clear that the issue is actually that the "Data" and "Copy Explorer link" are not easy to discover for users.

Rather than just applying the solution we went for desktop (which doesn't translate well to a mobile pattern), we should rather think about how we can improve the discoverability of this functionality similarly to what was done for the card layout.

We should therefore first evaluate other solution that are for mobile as part of UX research, before implementing it.

I am going to rename the issue and close https://github.com/ooni/probe/issues/1161 as duplicate of this one.

**Comment by lorenzoPrimi** [comment] 2020-05-22 13:17
If we do this we might want to have also a nicer json viewer #1156

**Comment by lorenzoPrimi** [comment] 2020-05-27 16:40
Phase #1: Log how many people click on options, data, logs, url, methodology (log test type)
Phase #2: Change copy to share explorer url and open the native share feature
Phase #3: Consider adding a Share button more visible that will share the Explorer URL and compare the metrics with phase #2

**Comment by hellais** [comment] 2020-05-28 16:28
Converted to epic and added the 3 phases as child issues.

**Comment by hellais** [comment] 2021-05-24 13:29
At this point this is a UX question.

**Closed** 2021-09-02 14:13 UTC
Labels: ooni/probe-mobile, ux, priority/low
