### ISSUE TITLE
UI issues based on font size in multiple part of the Android app (Exemple with the French translation)

### ISSUE THREAD

**Issue by notagoodidea** [ooni/probe#848] opened 2019-02-08 21:41 UTC
Multiple issues with the French Translation of Ooni Probe. Mainly, in multiple parts of the app, the French translation is longer than the original English but it number of characters is not constrained or screen space is not increased to fully show.

### 1. On the footer/Category Menu
When unselected the "Résultats des tests"' item is fully visible, if selected the "tests" part of "Résultats des tests" will be hidden on the next line. (Résultats des tests = Test results)

The screenshots are taken is with the font size set to *small*. When the font size is set at *really small*, there is no issue. 

![capture _2019-02-08-22-22-35](https://user-images.githubusercontent.com/22628160/52507045-ba583880-2bf0-11e9-9db1-98f5435b87b9.png)
![capture _2019-02-08-22-22-52](https://user-images.githubusercontent.com/22628160/52507051-c0e6b000-2bf0-11e9-9a5b-a4674269a5d4.png)

For information, the font size set at *really big* mess total the UI as seen below : 
![capture _2019-02-08-22-29-18](https://user-images.githubusercontent.com/22628160/52507272-53874f00-2bf1-11e9-960e-80173bbf37ee.png)

And between the two extreme font sizes, you see the issues for the footer but other parts of the app appears as the text grown bigger and bigger than the fixed size box available.

The issue will not be French-specific as it is related on the font size management inside the app. It seems like an accessibility issue. 

### 2. Unscrollable vertically top box in individual test result
Within the french translation, the text in the colored box on top of individual test result go lower than the space available. Unfortunately those panels are unscrollable vertically so the text is cut if half.

![capture _2019-02-08-22-23-26](https://user-images.githubusercontent.com/22628160/52507519-13749c00-2bf2-11e9-94c7-b0ff86c7efc4.png)
![capture _2019-02-03-22-17-24](https://user-images.githubusercontent.com/22628160/52507538-1d969a80-2bf2-11e9-85df-70cc9a34f1e0.png)

This issue is the related to the issue on top. With the font size set to *rellay small*, the text will fit correctly in the colored panel.

The issues are noticed with Android 8 and Ooni Probe 2.0.2 on a LG G6 (stock)

**Comment by notagoodidea** [comment] 2019-02-08 21:50
Seems related to [issue #845](https://github.com/ooni/probe/issues/845)

**Comment by elioqoshi** [comment] 2019-02-27 14:10
@notagoodidea thanks again for opening this issue!

As also said on Slack, this is a rather difficult issue to address and we have to figure out how. I just tried this on my own phone (One Plus 6) which has a huge display and could see the same problem, which was even worse if I have a little higher text size in my Phone Settings (left default text size, right larger text size):

![image](https://user-images.githubusercontent.com/5436686/53495653-a5105480-3aa0-11e9-8a60-c3e36c28a19c.png)

Some options we have:
- Limit the character count of these strings (I don't think 'Utilisation des donnes' is needed, maybe just 'Les données' instead? Sorry my french is inexistent, but you get my point). 
- Use icons instead of labels (not a big fan of this as they can end up not being completely clear)
- Change the UI pattern used here, which might be the way going forward if we don't find how to make this pattern work.

It would be great to have other thoughts on this. @holantonela ?

**Comment by elioqoshi** [comment] 2019-03-01 10:11
@notagoodidea as a first step it would be best to try to keep the strings to the bare minimum of length. Would you be able to help for the french part regarding that? For example `Temps total d'execution` could be `Temps total`, right? After that we can see what we can do with the UX.

@lorenzoPrimi is there any way to restrict the number of characters available for string translations in transifex?

**Comment by lorenzoPrimi** [comment] 2019-03-01 14:30
I don't know if there is a restriction but for sure there is a max lenght field.

**Comment by elioqoshi** [comment] 2019-03-01 14:47
That's it then. We should revisit the max length fields and communicate it to translators that they should update the translations

**Comment by notagoodidea** [comment] 2019-03-14 23:02
@elioqoshi Sorry I missed your answers. For the french translation, you can reduce the number of characters for "Utilisation des données" to "Données utilisées". Roughly "Data use" to "Data used". For the "Temps total d'execution", it will be trickier. I'm available to give a hand for the French translation. But I'm sure the same issue exist for other languages with lengthy words as German.

@elioqoshi @lorenzoPrimi  Is it possible to make the coloured panel vertically scrollable? It willmayb solve the problem and I think in a UX point of view, when a user sees text cut, he will try to scroll it (at least, I tried... generalization bias but who knows).

**Comment by hellais** [comment] 2021-05-24 13:45
This is a duplicate of: https://github.com/ooni/probe/issues/922

**Closed by hellais** 2021-05-24 13:45 UTC
Labels: ux
