### ISSUE TITLE
Improve discoverability of the "Choose websites" button

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#870] opened 2019-07-09 13:51 UTC
The "Choose websites" button is super important, as it enables users to test the URLs of their choice. This has repeatedly been requested by community members over the years and is arguably one of the most important features in the new OONI Probe mobile apps.

However, this very important feature is quite buried and as a result, many of our community members and users don't know that it's available in the mobile apps (i.e. many community members are surprised when I tell them that this feature is now supported!).

Currently, the "Choose websites" button is buried because the user needs to tap on the Websites card, while many users don't appear to tap on the card (even though we explicitly ask them to do so in the copy provided on the card).

**I therefore propose that we place the "Choose websites" button on the Websites card, along with the "Run" button.** 

Our previous designer had created a mockup which showed what it would look like having this button on the Websites card and, in my opinion, it didn't look bad. We ended up placing this button though inside the card instead for "consistency purposes", so that all cards would consistently only have one "Run" button.

I personally think that providing users with the features that they care about is more important than design consistency. 

I therefore strongly encourage our team to consider placing the "Choose websites" button on the Websites card, or any other place that makes it obvious and easy to find to all users.

**Comment by hellais** [comment] 2019-07-10 16:25
I think that this topic came up in the initial designs as well and we considered this option though it makes the UI inconsistent.

Moreover we also have other features inside of the card itself (example: the category selection) that if the problem is that it's unclear that the card is clickable we should solve that.

I am not sure this is the right solution, so I would rather we phrase this issue with as the problem we are trying to solve, that from what I understand is making the "Choose websites" button more discoverable, rather than stating a solution.

That way we can explore various ways in which we can solve that design problem rather than just implementing a solution which may not necessarily be the right one (I don't believe it's the right one and we excluded it in the initial design phase as well).

**Comment by holantonela** [comment] 2019-09-23 12:54
Testing specific websites is a cool feature, and early Probe user's or users under active censorship are the most fans of it. I think we can try two different options here with some copy iterations:

**1. Add Card**

As i said, i think this feature is core in OONI. What if we add a new card at the homepage? I'm using the same label we already have in the current version, just to stick to the l10n memory. Maybe we can try "Test a website", "Test a specific URL", or any other option you consider better.

<img src="https://user-images.githubusercontent.com/7602174/65426868-7d3f6000-dde7-11e9-8ea7-4f46ed5f5aca.jpg" width="200"/>

**2. Add Secondary Button**

We have enough room to add a secondary button at the main card. Ideally, we remove the "Choose Websites" button at /websites and we follow the same flow.

<img src="https://user-images.githubusercontent.com/7602174/65426869-7d3f6000-dde7-11e9-8d1f-a541d86626cf.jpg" width="200"/>

**Comment by agrabeli** [comment] 2019-10-11 14:18
Thank you @holantonela , both of your suggestions are great!

We initially tried option 2 in earlier mockups (before the launch of the revamped app), but it was dropped in the end because it was deemed inconsistent with the rest of the cards (which only have 1 button). 

I think none of us though considered your 1st suggestion, which is that of adding a separate, dedicated card for customized URL testing. I think that's a great suggestion and I personally vote for that! I agree with you that customized URL testing is a feature in itself and something that probably deserves equal prominence to the rest of the cards. It therefore makes a lot of sense to have a dedicated card for it. 

If @hellais @lorenzoPrimi etc agree with going for option 1, I'd be happy to write copy for the new card.

**Comment by lorenzoPrimi** [comment] 2019-10-14 00:20
Option 1 will push other card further down, it's a though decision.
Furthermore I wouldn't write "Run" there but "Choose websites" as it will not launch the run page when pressed.

**Comment by holantonela** [comment] 2019-10-15 11:49
So, what if we go with option 1, "Choose website" label, and also we have it in the first place?
![3](https://user-images.githubusercontent.com/7602174/66828881-7e683680-ef28-11e9-87be-3553075c43e5.jpg)

**Comment by agrabeli** [comment] 2019-10-15 11:55
@holantonela I would propose that we list the "Choose websites" card 2nd (right after the Bulk Websites card) because -- while it is an important feature -- we probably want people to contribute to general testing before narrowing down their testing to only a few specific sites.

**Comment by lorenzoPrimi** [comment] 2020-01-21 03:49
@hellais @agrabeli what are the final thoughts on this?

**Comment by hellais** [comment] 2020-01-27 13:31
I like the idea of adding a new card that allows a user to choose which website they can test. I think this also opens up the possibility of making this into a pattern to be used for more advanced tests.

The thing I am not so convinced about, though, is the copy to be used for these features.

I think we should have some wording inside of the "Bulk websites" card, that hints at the fact we are drawing from the citizenlab test-lists and that we draw from a list of curated testing lists.

The copy of the individual site testing also should mention that we in fact support multiple URLs and not just a single site.

One suggestion for the copy could be:

1. Automatic URL list
Check for accessibility of websites by automatically drawing global and country lists curated by experts. 

2. Manual URL list
Choose your own websites for testing

@agrabeli @holantonela what do you think?

**Comment by hellais** [comment] 2020-01-31 10:53
Need some input from @agrabeli and @holantonela on this. Moving to the next sprint.

**Comment by lorenzoPrimi** [comment] 2020-02-18 03:32
@hellais do we have a UX for this? should we proceed with the proposed one?

**Comment by hellais** [comment] 2020-02-18 17:43
@lorenzoPrimi this is still awaiting on input from @agrabeli and @holantonela related to the copy for the text.

Once we have the copy finalised we should proceed to making high resolution mockups for it and choosing some appropriate icons for the cards.

I suggest we discuss this during the next frontend weekly meeting. I think we should aim to have the mocks and UI finalised by the end of this sprint, ready for you to start implementing it during the next.

**Comment by holantonela** [comment] 2020-03-05 12:59
Back here. I can work on these mocks soon. @hellais can you point me to the latest editable files? @agrabeli what do you think about Arturo's suggestions in https://github.com/ooni/probe/issues/870#issuecomment-578747526?

**Comment by hellais** [comment] 2020-04-01 17:54
So I've spent some time thinking about this issue and I think that the solution to this should go hand in hand with the solution to the run all tests button (see: https://github.com/ooni/probe/issues/826).

I will spend a few words explaining the process I went through to come up with the solution which I will then share.

In order to come up with a solution to this I did a bit of research into how apps out there are dealing with similar patterns. In particular I looked at antivirus software which has a similar concept to the OONI "Run a network experiment", in their case they are talking about "Scan".

In the case of OONI Probe I would say that for most users we just want them to Run all the tests without any type of configuration. I think that if we add the ability to run all tests with a single button, we should not be further cluttering the UI with having an individual Run button for each test row, since the ability to trigger just an individual type of test is a power user feature.

That is why I have removed all the run buttons from the dashboard screen and replaced them with some very stripped down and simplified cards.

I think that by removing the Run button from the card itself we also address the issue that users aren't aware of the fact that you can actually click on the card, because it looks much closer to a material design card (it's elevated) and there is **no other action they can do it on it beyond tap on it**.

The primary action in this screen becomes just the single run button, which is the sane default and for power users they can tap on a card to learn more and do more advanced testing.

Here is the mockup for this screen: https://sketch.cloud/s/8vqJq/a/g2YPPq.

![Dashboard Revamp](https://user-images.githubusercontent.com/424620/78169924-765a6f80-7452-11ea-9147-3a4f0b730cd4.png)

With respect to the content of the card itself, not much changes are done, beyond just refreshing a bit the screen to make it more similar to the Run all button pattern used in the dashboard.

I also experimented a bit with a subtle gradient on the globe icon but I am actually not too convinced by it, more experimentation is maybe needed.

Here is the mockup for the details screen: https://sketch.cloud/s/8vqJq/a/8Qo77a.

![Websites Details](https://user-images.githubusercontent.com/424620/78169936-79edf680-7452-11ea-9fb5-0b93f7eaf9bb.png)

@holantonela @agrabeli what do you think of this solution?

**Comment by agrabeli** [comment] 2020-04-03 15:40
@hellais Huge +1 to your recommendation! I am super excited -- this proposal solves 2 problems ("Adding the Run All Tests button" + "Improving discover ability of Choose Websites button") with 1 solution. :) I particularly like that this solution does not involve creating clutter by adding more cards. 

I agree that by removing the "Run" button from the cards entirely, it becomes more obvious that users should tap on the card (where they can find all the options). I also agree that we probably want most users to just tap the "Run All Tests" button at the top anyway. I also like that by making the cards thinner (like in your mockup), it's possible to display more tests in one view.  

Huge thumbs up for this proposal!

**Comment by hellais** [comment] 2020-04-03 17:08
I made an extra variation of the test details screen, which I think works a bit better and helps further reduce some of the clutter of that screen too.

Here it is: https://sketch.cloud/s/8vqJq/v/g119vz/
![IM Apps](https://user-images.githubusercontent.com/424620/78386825-9028bd80-75de-11ea-821b-470e5097d72c.png)
![Websites Details Option B](https://user-images.githubusercontent.com/424620/78386826-90c15400-75de-11ea-8d72-71c94fdf56ca.png)

**Comment by agrabeli** [comment] 2020-04-06 10:19
@hellais thanks for the latest mockup of the test details screen. I think it works well -- I agree that this latest version helps reduce some of the clutter and makes it look more clean.

**Comment by hellais** [comment] 2020-04-13 11:03
The UX side of things is done. Follow up issue is this one: https://github.com/ooni/probe/issues/1094

**Closed by hellais** 2020-04-13 11:03 UTC
Labels: discuss, effort/M, ooni/probe-mobile, priority/medium, ux
