### ISSUE TITLE
Resolve progress bar being stuck while re-running tests

### ISSUE THREAD

**Issue by hellais** [ooni/probe#800] opened 2018-11-22 09:59 UTC
This affects for sure iOS, but probably also Android.

When you re-run a test the ETA is set to 35 seconds, but since it's a single input it will appear to be stuck at 32seconds (or 10%) for quite some amount of time and may appear to not be advancing.

We should maybe come up with a better way of advancing the progress bar so that it advances also when there isn't an explicit "percentage" event coming from measurement-kit.

cc @lorenzoPrimi

**Comment by lorenzoPrimi** [comment] 2018-12-04 15:01
Yes it affects also Android due to the algorithm. @xanscale
What is your suggestion? Should we do it in 2.1?

**Comment by xanscale** [comment] 2018-12-05 18:36
actually we have a stubbed runtime for each suite of test, so when we run only one test of that suite (ooni-run or re-run) we have problem to update progress bar and estimate the ETA.

i suggest to move stubbed runtime inside each single test. so suite runtime become summary of real current running tests of that suite.

**Comment by hellais** [comment] 2018-12-06 10:06
@xanscale I believe what you are referring to is this other issue: https://github.com/ooni/probe/issues/805.

In this case it's not enough to move the ETA into a single test, because, for example, in the case of websites it will still appear to be "stuck" at 35 seconds while you are re-running a single test.

My suggestion for a fix to this issue would be that we make the progress bar and eta counter move also in absence of an event from measurement kit.

Here is a concrete example, supposing the user has re-run a websites test for a single URL and assuming the total runtime is of an individual URL is 50s (for simplicity sake):

1. User taps re-run
2. App get's the 10% event from MK, it's showing the ETA of 45s 
3. The progress bar keeps moving towards 100% at a rate such that it will reach 100% in 45 seconds (ex. after 5 more seconds, the bar will be at 20% and the ETA at 40s)
4. The app get's the event 50% from MK, it advances (or goes back) to 25s and shows 50% progress
5. etc.

The problem with this approach is that if we are underestimating the runtimes, the progress bar may end up going back (windows progress bar effect!), on the other hand this allows us to have the bar moving at any given time, independently from the progress events (so it will never appear stuck).

What do you think?

**Comment by xanscale** [comment] 2018-12-06 11:03
(personally i hate "fake" progress)

actually we create progress based on all suite, so if you run only 1 test of suite you can go only from 0% to 30% (for example)

so even mk post an update, seams very little


i think that if we solve other bug this could be reduced a lot

**Comment by lorenzoPrimi** [comment] 2018-12-06 17:10
As @hellais said, moving the runtime inside the single test will optimize much more the runtime calculation in the future but wont solve this specific problem: 1 url + timeout.
I guess @xanscale you should propose you solution in #805

**Comment by lorenzoPrimi** [comment] 2018-12-11 17:11
@hellais here are the algorithms

iOS:
	Websites test with max_runtime
	https://github.com/ooni/probe-ios/blob/master/ooniprobe/View/RunTest/TestRunningViewController.mm#L15
	Websites test without max_runtime
	https://github.com/ooni/probe-ios/blob/master/ooniprobe/View/RunTest/TestRunningViewController.mm#L34
	Get runtime
	https://github.com/ooni/probe-ios/blob/master/ooniprobe/Utility/TestUtility.mm#L178
	Algo that updates progress bar
	https://github.com/ooni/probe-ios/blob/master/ooniprobe/View/RunTest/TestRunningViewController.mm#L126
	
Android:
	Websites test with max_runtime
	https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java#L71
	Websites test without max_runtime
	https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java#L78
	Get runtime
	https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/test/suite/AbstractSuite.java#L111
	https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/test/suite/InstantMessagingSuite.java#L28
	https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/test/suite/MiddleBoxesSuite.java#L27
	https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/test/suite/PerformanceSuite.java#L27
	https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/test/suite/WebsitesSuite.java#L24
	Algo that updates progress bar
	https://github.com/ooni/probe-android/blob/master/app/src/main/java/org/openobservatory/ooniprobe/activity/RunningActivity.java#L161

**Comment by lorenzoPrimi** [comment] 2020-01-20 04:06
@hellais @bassosimone any idea about this? 
in case of one single url the time is 5 sec (one url) + 30 sec (timeout)

**Comment by lorenzoPrimi** [comment] 2020-01-21 02:21
@hellais let's start the discussion

**Comment by hellais** [comment] 2020-01-24 16:31
We discussed this with @bassosimone and we agree that the correct implementation for this is what I outlined in: https://github.com/ooni/probe/issues/800#issuecomment-444818337.

@lorenzoPrimi how much effort do you think is required to do this? Any problems with this approach?

**Comment by lorenzoPrimi** [comment] 2020-01-25 04:35
@hellais what is not clear is if we  use this approach only when we have one single URL or always. Because when we test a X number of URLs the progress bar works just fine and wouldn't be nice to make it progress and go back, progress and go back.

**Comment by hellais** [comment] 2020-01-27 09:22
> what is not clear is if we use this approach only when we have one single URL or always. Because when we test a X number of URLs the progress bar works just fine and wouldn't be nice to make it progress and go back, progress and go back.

I think you want to apply this logic of making the progress bar walk forward when it's at the last percentage increase. For example if you are testing 100 URLs, you would have it move automatically only when it reaches URL number 99. The case of a single URL is the special case of the first URL being also the last URL.

Does this make sense?

**Comment by lorenzoPrimi** [comment] 2020-01-27 11:05
So only in the case of event "submitting report please be patient" ?

**Comment by hellais** [comment] 2020-01-27 13:01
> So only in the case of event "submitting report please be patient"

Only when, given N inputs, you are processing input number N. If N = 1, as is the reported case, this results in being applied at the beginning of it, while for larger numbers you only start making the progress bar walk automatically at the end.

Does this make sense?

**Comment by lorenzoPrimi** [comment] 2020-01-28 03:02
Ok so when there are N inputs (so max_runtime = -1) at the N-1 input I make the progressbar go forward every second.
If max_runtime has a real value I make the progress bar go forward only in the last 30 seconds (submitting report please be patient)

**Comment by lorenzoPrimi** [comment] 2020-01-29 04:47
I just realised that in any case the progress bar is stuck only in the last 30 seconds, until that it works perfectly. 
And it's stuck only when there are many URLS, if only one URL is tested the submission is almost instantly.

Amyway we can implement the progress second by second when remaining time < 30.

Furthermore we need to remove the (+30) seconds from the websites test when `automatically publish results` is not selected.

**Comment by hellais** [comment] 2020-01-29 08:10
> I just realised that in any case the progress bar is stuck only in the last 30 seconds, until that it works perfectly.
> And it's stuck only when there are many URLS, if only one URL is tested the submission is almost instantly.

On which sort of network did you validate these assumption on? I suspect the user experience will vary significantly depending on the latency to the backend and overall network performance.

> Amyway we can implement the progress second by second when remaining time < 30.

I think that rather than making it dependent on a fixed time value, we should use the fact that if you are at the last input in the list, the only possible last increment in the final one of completion and hence it should advance at a regular pace until it reaches conclusion.

> Furthermore we need to remove the (+30) seconds from the websites test when automatically publish results is not selected.

I am not sure we want to do this, there is still overhead caused by some other backend communication (ex. getting the test list) and I think we are better off not complicating this logic too much if we don't need to.
After-all if the test is faster than expected, that is good for the user.

**Comment by hellais** [comment] 2020-01-31 11:31
We discussed this with @lorenzoPrimi and it appears that MK may emit enough events that make this behaviour not as common as was originally thought.

@lorenzoPrimi can you update this issue with information on the testing you have done to verify that maybe this issue doesn't happen anymore and/or what more testing/information is needed in order to move it forward?

**Comment by hellais** [comment] 2020-01-31 12:00
So I went ahead and tested this in iOS and Android and it's still an issue. It stays stuck on the 32 second mark for almost 2 minutes in my tested cases

Video for iOS: https://youtu.be/aDjhjG9zIHU

On Android there is an additional issue, which is that for some seconds in the beginning, during a normal test run, no ETA indiciator at all is displayed see:
![IMG_7556](https://user-images.githubusercontent.com/424620/73537352-8b059180-4428-11ea-9e29-f7cb00e82451.JPG)

Similarly to iOS on Android the progress is stick for more than a minute saying 32 seconds: https://youtu.be/aAQhjgKRUYU

**Comment by lorenzoPrimi** [comment] 2020-02-02 12:52
Just seen the iOS video. So the problem is with rerun algorithm, my bad I was running test normally.
There are events and the progress bar is not updated. Will look into it.

About Android we already discussed this in another ticket, there is no progress  because the test is not yet running, in fact you see "Preparing test" and not "Running websites"

**Comment by hellais** [comment] 2020-02-03 11:36
> Just seen the iOS video. So the problem is with rerun algorithm, my bad I was running test normally.
> There are events and the progress bar is not updated. Will look into it.

Please prioritise looking into fixing this for Android, which exhibits the same issues as iOS.

> About Android we already discussed this in another ticket, there is no progress because the test is not yet running, in fact you see "Preparing test" and not "Running websites"

Can you provide a link to that?
Can we instead of showing an empty ETA, display something, even "Calculating ETA" or ideally the ETA we know from the summary estimates?

I also think the progress bar should start with a little bit of populated progress to give the impression that something is happening. As it is the screen looks like something if off.

**Comment by lorenzoPrimi** [comment] 2020-02-07 07:29
> Can we instead of showing an empty ETA, display something, even "Calculating ETA" or ideally the ETA we know from the summary estimates?
Should I change the copy from Preparing test to Calculating ETA? or adding a new label?

**Comment by hellais** [comment] 2020-02-07 08:30
> Should I change the copy from Preparing test to Calculating ETA? or adding a new label?

I think it's fine if we leave the preparing test string and just adjust the bottom section of this screen with a new string.

The most important part of this is making the progress bar be filled and stripped to indicate that something is happening, but it's unclear when it will finish.

If you can look into some existing components or tell me how you need me to prepare the animation/illustration I can work on it.

Here is a quick mockup of how it should look:
![Screenshot 2020-02-07 at 09 28 20](https://user-images.githubusercontent.com/424620/74013230-4334bc00-498c-11ea-8ccf-cdb65290e6e5.png)

**Comment by lorenzoPrimi** [comment] 2020-02-08 04:01
Do you think this should be included in the release? I think can be a long task, so in case it should go there, the release should be pushed further.

**Comment by lorenzoPrimi** [comment] 2020-02-09 08:31
I did some research into it, when testing one single URL I get not enough events:
```
2020-02-09 16:29:58.419852+0800 ooniprobe[27328:1219909] Got event: {
    key = "status.progress";
    value =     {
        message = "starting the test";
        percentage = "0.1";
    };
}
2020-02-09 16:29:58.420311+0800 ooniprobe[27328:1219909] Got event: {
    key = "status.progress";
    value =     {
        message = "Processing input: https://www.ilga-europe.org/";
        percentage = "0.1";
    };
}
2020-02-09 16:29:57.057051+0800 ooniprobe[27328:1219909] Got event: {
    key = "status.progress";
    value =     {
        message = "geoip lookup";
        percentage = "0.05";
    };
}
2020-02-09 16:31:12.554970+0800 ooniprobe[27328:1219909] Got event: {
    key = "status.progress";
    value =     {
        message = "ending the test";
        percentage = "0.95";
    };
}
```

@bassosimone should we discuss this on the 1-on-1?

**Comment by lorenzoPrimi** [comment] 2020-02-18 15:02
In the call of today me and @bassosimone we stated that this fix will be done mk side.

I split this into another issue that will be done soon because doesn't require any mk changes https://github.com/ooni/probe/issues/1020

**Comment by bassosimone** [comment] 2020-02-24 10:13
My suggestion for fixing the issue is that we set an upper bound timeout into a Go context and the code simply stops working and returns an error when the timeout is expired. This seems to me the same problem of the progress bar. In such model, in fact, we could guarantee the maximum duration of an experiment with N input URLs. Therefore, the progress bar can just show the elapsed time.

**Comment by bassosimone** [comment] 2021-02-10 07:12
@lorenzoPrimi is this still an issue?

**Comment by lorenzoPrimi** [comment] 2021-02-10 10:15
Ran a test with one url only and doesn't seem stuck at all. closing.

**Closed by lorenzoPrimi** 2021-02-10 10:15 UTC
Labels: bug, discuss, effort/L, ooni/probe-mobile, platform/android, platform/ios, priority/medium, ux
