### ISSUE TITLE
Localize "Psiphon experiment running" when the Psiphon test runs

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#1148] opened 2020-05-04 18:23 UTC
English should not be displayed in the localized UI. We need to push the string "Psiphon experiment running" to Transifex so that it can be translated.

![2020-04-24 Psiphon experiment running appears in English in the localized UI](https://user-images.githubusercontent.com/8290574/80999499-1554fb80-8e45-11ea-9a15-62f09e95089d.png)

**Comment by agrabeli** [comment] 2020-05-04 18:26
We should probably ensure that this string is added to transifex for translation before the new circumvention tool tests are integrated into the mobile app. cc' @lorenzoPrimi

**Comment by hellais** [comment] 2020-05-05 09:38
This is a duplicate of https://github.com/ooni/probe/issues/1150. I explain in this comment why this is the case: https://github.com/ooni/probe/issues/1150#issuecomment-623955107.

I am closing this issue.

**Closed by hellais** 2020-05-05 09:38 UTC
Labels: duplicate
