### ISSUE TITLE
Add support for automated testing of full test lists

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#917] opened 2019-09-04 10:14 UTC
Currently Android OONI Probe users only test a random selection of URLs -> as many as they can connect to within 90 seconds. Many users though are interested in testing the full test lists (global + country-specific) automatically on a daily basis.

Once automated testing is re-added to the OONI Probe Android app (per https://github.com/ooni/probe-android/issues/245), it would be great to add support (in future releases) for automatic testing of full test lists. This could be an option that users can choose through the (new) "Automated testing" settings in the app.

This feature requires that we know that the user is connected to WiFi, and that this automated testing of full test lists (which can involve thousands of URLs) is only performed when the user is connected to WiFi (and stops as soon as they are disconnected or switch to data).

**Comment by lorenzoPrimi** [comment] 2020-01-17 10:39
I think  this is a duplicate of https://github.com/ooni/probe/issues/893 and can be closed

**Comment by lorenzoPrimi** [comment] 2020-01-17 11:37
@agrabeli is what we implemented now* what you wanted ?
* Possibility to disable max_runtime and test the entire test list

**Comment by agrabeli** [comment] 2020-01-17 18:46
@lorenzoPrimi yes, thank you. This is very exciting! Thank you for working on this. :)

**Comment by agrabeli** [comment] 2020-01-17 18:52
@lorenzoPrimi Sorry, I commented without having read my own text above and I misunderstood. While what you implemented is fantastic (i.e. having the ability to disable max runtime in the app), this issue is a bit different: it requests the automated testing of the full test list. Essentially, once Automated testing is re-introduced to the app, then it's a question of adding support for the automated testing of the full test list (without requiring users to know to manually disable the max runtime).

**Comment by hellais** [comment] 2020-08-31 10:44
Closed in favour of the epic: https://github.com/ooni/probe/issues/916

**Closed by hellais** 2020-08-31 10:44 UTC
Labels: enhancement, ooni/probe-mobile, priority/medium
