### ISSUE TITLE
Make it easy to access the logs in the OONI Probe mobile apps

### ISSUE THREAD

**Issue by agrabeli** [ooni/probe#882] opened 2019-09-20 14:55 UTC
Currently, when people report issues with the OONI Probe mobile app, it's hard to identify the issue and help out unless the OONI dev team looks at the logs.

However, finding/accessing the logs based on the UX of the current OONI Probe mobile app is not straightforward, and it usually requires spending time explaining to people step by step how to eventually find the logs and share them with developers.

To improve our troubleshooting processes and better serve our community, it would be great if we could think about how to make it easier for users to find/access the logs in the OONI Probe mobile apps.

**Comment by agrabeli** [comment] 2019-09-20 15:00
Perhaps one way to solve this problem is to add buttons for "Data" and "Logs" on the measurement pages themselves (along with the "Methodology" button), and to remove the settings (on the top right corner) from the measurement pages entirely.

@holantonela what do you think?

**Comment by lorenzoPrimi** [comment] 2019-09-21 09:16
@agrabeli remember that logs are deleted after the measurement has been uploaded and processed, so approximately after 24 hours.

**Comment by sarathms** [comment] 2019-09-23 13:26
I second the idea to introduce buttons on the measurement page to show data and logs. Is there a reason why these actions were tucked into the top-right menu?

**Comment by lorenzoPrimi** [comment] 2020-05-25 13:45
Duplicate of #1160

**Closed by lorenzoPrimi** 2020-05-25 13:45 UTC
Labels: enhancement, ooni/probe-mobile, ux
